version: 2.1
orbs:
  nais: navikt/nais-deployment@3.2.1

jobs:
  bygg:
    docker:
    - image: circleci/openjdk:11
    steps:
    - checkout
    - restore_cache:
        keys:
          - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          - maven-repo-v1-{{ .Branch }}-
          - maven-repo-v1-
    - run:
          name: Bygger med Maven
          command: mvn clean package
    - save_cache:
        paths:
          - ~/.m2
        key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
    - nais/docker:
        image: navikt/altinn-rettigheter-proxy

workflows:
  version: 2.1
  bygg_og_deploy:
    jobs:
      - bygg:
          context: NAIS deployment
