apiVersion: nais.io/v1
kind: Alert
metadata:
  name: altinn-rettigheter-proxy-alert
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: arbeidsgiver-msa-alerts
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: absent(up{app="altinn-rettigheter-proxy", job="kubernetes-pods"})
      for: 1m
      description: "altinn-rettigheter-proxy er nede"
      action: "Sjekk https://logs.adeo.no/goto/ae771c0e74a1d23b935a4af2f79144c6 for logger, og Grafana-dashboardet vårt: https://grafana.nais.io/d/X7LCJ49Wk/team-msa-altinn-rettigheter-proxy"

    - alert: det har skjedd en feil i altinn-rettigheter-proxy
      expr: sum(increase(logd_messages_total{log_app="altinn-rettigheter-proxy",log_level="Error"}[5m])) > 0
      for: 10s
      description: "altinn-rettigheter-proxy har logget en feil"
      action: "Sjekk https://logs.adeo.no/goto/ae771c0e74a1d23b935a4af2f79144c6 for logger, og Grafana-dashboardet vårt: https://grafana.nais.io/d/X7LCJ49Wk/team-msa-altinn-rettigheter-proxy"
