apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: altinn-rettigheter-proxy-alert
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'arbeidsgiver-teamia-utvikling'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: sum(up{app="altinn-rettigheter-proxy", job="kubernetes-pods"}) == 0
      for: 1m
      description: "altinn-rettigheter-proxy er nede"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.adeo.no/d/MwhvlzSMz/team-ia-samledashboard"

    - alert: det har skjedd en feil i altinn-rettigheter-proxy
      expr: sum(increase(logd_messages_total{log_app="altinn-rettigheter-proxy",log_level="Error"}[5m])) > 0
      for: 10s
      description: "altinn-rettigheter-proxy har logget en feil"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.adeo.no/d/MwhvlzSMz/team-ia-samledashboard"
