apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: arbeidsgiver
  name: altinn-rettigheter-proxy-redis
  namespace: default
spec:
  image: navikt/secure-redis:5.0.3-alpine-2
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
  vault:
    enabled: true

---

apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: arbeidsgiver
  name: altinn-rettigheter-proxy-redisexporter
  namespace: default
spec:
  image: navikt/secure-redisexporter:v0.29.0-alpine-3
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  vault:
    enabled: true
  env:
    - name: REDIS_ADDR
      value: altinn-rettigheter-proxy-redis.default.svc.nais.local:6379
