name: Build & deploy

on: [push, workflow_dispatch]

env:
  IMAGE_BASE: ghcr.io/${{ github.repository }}/altinn-rettigheter-proxy
  IMAGE: ghcr.io/${{ github.repository }}/altinn-rettigheter-proxy:${{ github.sha }}
  
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - run: mvn -B test

  build:
    name: Build
    needs: test
    #########################
    ### DEVELOPERS: Insert your feature branch name below (in addition to master) if you want to deploy it to dev
    #########################
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/snyk-fix-51ccaeacfc76b13c3d991e6bafda6d8d'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
      - run: mvn -B package -DskipTests
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}
            ${{ env.IMAGE_BASE }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_BASE }}:latest
          cache-to: type=inline

  ###### GCP DEV
  deploy-server-dev-gcp:
    name: Deploy server dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/dev-gcp.yaml

  ###### GCP PROD
  deploy-server-prod-gcp:
    name: Deploy server prod-gcp
    needs: deploy-server-dev-gcp
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/prod-gcp.yaml
