name: Deploy Redis 2

on:
  push:
    paths: ['nais/redis-2-gcp.yaml']
  workflow_dispatch:

jobs:
  ###### GCP PROD 2
  deploy-redis2-prod-gcp:
    name: Deploy redis prod-gcp
    if: github.ref == 'refs/heads/maskinport1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/redis-2-gcp.yaml
