name: Deploy Redis

on:
  push:
    paths: ['nais/redis-gcp.yaml', 'nais/redis-dev-gcp.yaml', 'nais/redis-prod-gcp.yaml']
  workflow_dispatch:

jobs:
  deploy-redis-dev-gcp:
    name: Deploy redis dev-gcp
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/TAG-1787'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/redis-gcp.yaml
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/redis-dev-gcp.yaml

  deploy-redis-prod-gcp:
    name: Deploy redis prod-gcp
    needs: deploy-redis-dev-gcp
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/redis-gcp.yaml
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/redis-prod-gcp.yaml
